### ISSUE TITLE
Sample data not working

### ISSUE THREAD

**Issue by hamsho93** [seanclaude/Redistricting#3]
Hello,

When I try and use the sample data in the plugin as pictured in the document below, I get a notification to "Please specify a value greater than 0". I have all the values placed and I am not sure which value it is referring to. Any advice?

[qgis_issue.docx](https://github.com/seanclaude/Redistricting/files/1305132/qgis_issue.docx)

**Comment by seanclaude** [comment]
The error I'm getting under linux is to use an integer field and it looks like it's because of not handling 64-bit fields. The fix is changing line 919 in redistricting_dock.py to

`if not provider.fields().at(provider.fieldNameIndex(self.context_fieldname)).isNumeric(): `

**Comment by seanclaude** [comment]
The error I'm getting under linux is to use an integer field and it looks like it's because of not handling 64-bit fields. The fix is changing line 919 in redistricting_dock.py to

`if not provider.fields().at(provider.fieldNameIndex(self.context_fieldname)).isNumeric(): `
