### ISSUE TITLE
Upgrade to QGIS 3? 

### ISSUE THREAD

**Issue by mrfnord** [seanclaude/Redistricting#4]
QGIS 2 is no longer available, and QGIS 3 doesn't allow the plugin to run.

**Comment by seanclaude** [comment]
Any specific use case that would make this a necessity? Due to breaking changes introduced by QGIS3, it is very likely that the UI will be different as well.

**Comment by seanlinmt** [comment]
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

I will try to complete the migration before the above date. Anyone who wants to contribute some help is welcomed to do so too.

**Comment by seanclaude** [comment]
upgrade to QGIS 3 done
